/*
 * This source file was generated by the Gradle 'init' task
 */
//package org.example;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper();
        InputStream is = App.class.getClassLoader().getResourceAsStream("trade.json");
        Trade trade = mapper.readValue(is, Trade.class);

        System.out.println("Symbol: " + trade.symbol);
        System.out.println("Quantity: " + trade.quantity);
        System.out.println(new App().getGreeting());
    }
}
